apiVersion: apps/v1
kind: Deployment
metadata:
     name: my-app-deployment
     labels:
        app: todo-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-todo-app-pod
  template:
     metadata:
         labels:
            app: my-todo-app-pod
     spec:
         containers:
           - name: my-todo-app-container
             image: my-img
             ports:
               - containerPort: 8000
  
          
     