apiVersion: v1
kind: Service
metadata:
   name: my-todo-app-svc
   labels:
      app: my-app-svc
spec:
   type: NodePort
   selector:
       matchLabels:
          app:my-todo-app-pod

   ports:
    -  port: 8000
       targetPort: 8000
       nodePort: 85
       protocol: TCP
